### ISSUE TITLE
[Request] Install guide

### ISSUE THREAD

**Issue by cjwyett** [konimex/kiss-llvm#4]
This looks very interesting. Is there any chance we could get a guide for a LLVM based kiss install? I appreciate that there is already a bit of instruction, but I was hoping for more of a step-by-step, like a slightly modified version of [this](https://k1ss.net/install)

Best wishes,

**Comment by konimex** [comment]
First of all, apologies for the late reply.

Step by step, from KISS installation from ground up up to changing the base to LLVM it should be identical to KISS. However, I'll see what I can do (by modifying KISS' instruction and save it (an `INSTALL` file, perhaps?), or adding a wiki page for KISS, I'm not sure), for now I'm keeping this issue open as a reminder for myself too.

**Comment by konimex** [comment]
Added in https://github.com/konimex/kiss-llvm/blob/35b5a005c200defdbb6ead5461ec769c761c5244/INSTALL
